#  _    _ _   _           _                      _             _
# | | _(_) |_| |_ _   _  | |_ ___ _ __ _ __ ___ (_)_ __   __ _| |
# | |/ / | __| __| | | | | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | |
# |   <| | |_| |_| |_| | | ||  __/ |  | | | | | | | | | (_| | |
# |_|\_\_|\__|\__|\__, |  \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|
#                 |___/              _          _   _
#   ___ _   _ ___| |_ ___  _ __ ___ (_)______ _| |_(_) ___  _ __
#  / __| | | / __| __/ _ \| '_ ` _ \| |_  / _` | __| |/ _ \| '_ \
# | (__| |_| \__ \ || (_) | | | | | | |/ / (_| | |_| | (_) | | | |
#  \___|\__,_|___/\__\___/|_| |_| |_|_/___\__,_|\__|_|\___/|_| |_|

##########################################################################

# темы
#include Wryan.conf
#include VSCode_Dark.conf

# непрозрачность и размытие терминала
background_opacity 0.85
background_blur 1

# расширенные настройки
term xterm-kitty

# звуковой сигнал терминала
enable_audio_bell no

# настройки, специфичные для ОС (декорация окон Gnome для Wayland)
#linux_display_server x11

# шрифт
font_family        JetBrainsMono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          11.0

# управление размером шрифта
map ctrl+shift+backspace change_font_size all 0

# настройка курсора
# блок / луч / подчеркивание
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# скроллинг
scrollback_lines 5000
wheel_scroll_multiplier 10.0
wheel_scroll_min_lines 1
sync_to_monitor yes

# мышь
mouse_hide_wait -1

# макет окна
remember_window_size  no
initial_window_width  1200
initial_window_height 750
window_border_width 1.5pt
enabled_layouts tall
window_padding_width 0
window_margin_width 2
hide_window_decorations no

# управление окнами
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# управление макетом
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# настройка панели вкладок
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# управление вкладками
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
#include current-theme.conf
# END_KITTY_THEME

# Палитра Zephyrine (вне блока KITTY_THEME — kitten themes его перезаписывает)
include zephyrine.conf
